import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Private evidence file storage on local disk under STORAGE_DIR (default
 * ./storage). Never under public/. Keys are generated here, never taken from
 * user input, and every resolved path is checked to stay inside the root.
 */
function root(): string {
  // Runtime data, not build input: keep the bundler from tracing the storage directory.
  return path.resolve(/*turbopackIgnore: true*/ process.env.STORAGE_DIR ?? "storage");
}

function resolveKey(key: string): string {
  const r = root();
  const full = path.resolve(/*turbopackIgnore: true*/ r, key);
  if (!full.startsWith(r + path.sep)) throw new Error("Storage key escapes storage root.");
  return full;
}

export async function saveEvidenceFile(clientId: string, ext: string, bytes: Uint8Array): Promise<string> {
  // Ids are generated by the database; allow only characters that cannot form a path segment like "..".
  if (!/^[a-z0-9_-]+$/i.test(clientId) || !/^[a-z0-9]+$/.test(ext)) throw new Error("Invalid storage key parts.");
  const key = `evidence/${clientId}/${randomUUID()}.${ext}`;
  const full = resolveKey(key);
  await mkdir(/*turbopackIgnore: true*/ path.dirname(full), { recursive: true });
  await writeFile(/*turbopackIgnore: true*/ full, bytes, { flag: "wx" });
  return key;
}

export async function readEvidenceFile(key: string): Promise<Buffer> {
  return readFile(/*turbopackIgnore: true*/ resolveKey(key));
}

export async function deleteEvidenceFile(key: string): Promise<void> {
  await rm(/*turbopackIgnore: true*/ resolveKey(key), { force: true });
}
